// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wslyglkkxyjevgofytpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzbHlnbGtreHlqZXZnb2Z5dHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODY4NjksImV4cCI6MjA3MDc2Mjg2OX0.pR6wIVg_oSp4Pudn9saChTwl6eyTRYaDggL0ZqeXeaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});